spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    template:
      default-topic: library_event
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: 1
        retries: 15
        retry.backoff.ms: 120
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094